<h1>Liste des utilisateurs</h1>
<?php if( !empty($users) ): ?>
<ul>
    <?php foreach( $users as $user ): ?>
        <li>
            <h2><?php printf( '%s %s', $user->getFirstname(), $user->getLastname() ) ?></h2>
            <ul>
                <li>Id: <?php echo $user->getId() ?></li>
                <li>Email: <?php echo $user->getEmail() ?></li>
                <li>Prénom: <?php echo $user->getFirstname() ?></li>
                <li>Nom: <?php echo $user->getLastname() ?></li>
                <li>Téléphone: <?php echo $user->getPhoneNumber() ?></li>
            </ul>
        </li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucun utilisateur inscrit.</div>
<?php endif ?>